[package]
name = "chog-cli"
version = "0.2.0"
edition = "2021"
description = "View and manage CHANGELOG.md files in the style of Keep a Changelog."
categories = ["command-line-utilities", "development-tools"]
keywords = ["changelog", "manage", "version"]
readme = "README.md"
repository = "https://github.com/sonro/chog"
license = "MIT/Apache-2.0"

[dependencies]
chog = { version = "0.2.0", path = "../lib" }
